version: '3'

services:
  nodejs-app:
    build:
      context: ./docker
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - ./app:/usr/src/app
    depends_on:
      - redis

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"